name: nocturne
channels:
  - defaults
dependencies:
  - python=3.8
  - gcc_linux-64
  - gxx_linux-64
  - pip=23.3.1
  - setuptools=66.0.0
  - numpy=1.19.2
  - jupyterlab=3.0.14
  - wheel=0.38.4
  - pip:
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.1.5
    - ipdb==0.13.9
    - seaborn==0.12.0
    - imageio==2.10.1
    - moviepy==1.0.3
    - opencv-python==4.5.5.64
    - "git+https://github.com/openai/gym.git@9180d12e1b66e7e2a1a622614f787a6ec147ac40"
    - wandb==0.12.15
    - imageio==2.10.1
    - setproctitle==1.2.3
    - tensorboardX==2.5
    - pytest==7.1.1
    - flake8==4.0.1
    - pydocstyle==6.1.1
    - pyvirtualdisplay==3.0
    - ray==1.11.0
    - dm-tree==0.1.8
    - tabulate==0.9.0
    - torch==1.13.0
    - sample-factory==1.123.0
